Add files via upload

diff --git a/usr/local/recentchanges/scripts/rntchangesfunctions b/usr/local/recentchanges/scripts/rntchangesfunctions
--- a/usr/local/recentchanges/scripts/rntchangesfunctions
+++ b/usr/local/recentchanges/scripts/rntchangesfunctions
@@ -114,22 +114,26 @@ EOF
 }
 
 setup_exports() {
+
     [[ "$1" = "gui" ]] && { "$app_install"/recentchanges ; exit ; }
     export CMD_LINE="1"
     [[ "$1" = "query" ]] && { "$app_install"/recentchanges "$USR" "$PWD" query ; exit ; }
     [[ "$1" = "reset" ]] && { "$app_install"/recentchanges "$USR" "$PWD" reset ; exit ; }
-   
+
     output=$( python3 "$app_install"/src/get_exports.py $USR) ; res=$?
 
     if [[ $res -ne 0 ]]; then
+        
         if [[ $res -eq 3 ]]; then
             echo "no key found"  # if there is a .gpg in /home/guest/.local/share/recentchanges but now there isnt a gpg key generatekey will clear it the .gpg
         elif [[ $res -eq 4 ]]; then
             echo "inappropriate ioctl or no pinentry." ; echo "if having problems run recentchanges reset" && exit 4
         elif [[ $res -eq 7 ]]; then 
             echo "bad passphrase" && exit 7
+        elif [[ $res -eq 2 ]]; then
+            echo "failed to start user gpg agent" && exit 2
         else
-            echo "couldnt start user gpg agent before root" && exit $res
+            echo "failed to setup environment from $app_install/src/get_exports.py" && exit $res
         fi
     fi
 
@@ -268,7 +272,7 @@ if [ "$ino" -ge 0 ] 2>/dev/null && [ "$sze" -ge 0 ] 2>/dev/null; then
                 modified_epoch=$c
                 change_time="$f3 $f4"
                 r=$( date -d "$change_time" +%s.%N 2>/dev/null)
-                [[ -n "$r" ]] && r=$(normalize_ts "$r") || log_lineout $debug_log $debug_file "$log_date" "calculate_csum Warning ct is null on retried. retry $(( max_retries - x ))" && return 1
+                [[ -n "$r" ]] && r=$(normalize_ts "$r") || { log_lineout $debug_log $debug_file "$log_date" "calculate_csum Warning ct is null on retried. retry $(( max_retries - x ))" ; return 1 ; }
                 ctime_epoch=$r
                 prev_hash="$checks"
                 sleep $delay
@@ -372,9 +376,13 @@ if [ -e "$cFILE" ] && [ -f "$cFILE" ]; then
 
                         output="$mt \"$y\" $ct $i $ats $adtcmd $cam $lmt $nlinks $mtime_us"
 
+                        flock -x 200
+
                         if [[ "$cache_flg" = "true" ]] && (( fs > 1000000 )); then [[ -d $cdir ]] || mkdir -p $cdir ; z="$( escf "$cFILE")" ; upt_cache "$i" "$fs" "$mtime_us" "$check_sum" "$z" "$6" ; fi
 
                         printf '%s\n' "$output" >> $2
+
+                        flock -u 200
 
                     else
                         log_lineout $7 $8 "$log_date" "pblk failed to process. itime $itime and mtime $mtime ctime was <= mtime skipped. line $1"
